Hw thread
Mandybur800/Work-with-threads pull request #1
Opened 2021-02-22 10:48 UTC by Mandybur800

2021-02-22 11:39 UTC, YuraBondarenko approved these changes

2021-02-22 15:58 UTC, Sofasmile requested changes

2021-02-22 15:58 UTC, Sofasmile commented on src/main/java/Main.java
> +        ThreadExample threadExample1 = new ThreadExample(counter);
```suggestion
        ThreadExample threadExample = new ThreadExample(counter);
```

2021-02-22 15:58 UTC, Sofasmile commented on src/main/java/RunnableExample.java
> +            counter.setCount(count);
давай створимо метод increment() в класі Counter який буде збільшувати поточне значення на 1 і повертати нове значення. Його ми і будемо логувати

2021-02-22 16:16 UTC, Sofasmile requested changes

2021-02-22 16:16 UTC, Sofasmile commented on src/main/java/RunnableExample.java
> +            counter.increment();
щось тут є трохи зайвого. Спробуй перечитати мій попередній коментар і використовувати increment метод

2021-02-22 16:22 UTC, Mandybur800 commented on src/main/java/RunnableExample.java
> +            counter.increment();
Так, ти права, тепер зрозумів що таке гонка потоків)

2021-02-23 07:58 UTC, Sofasmile approved these changes

2021-02-23 13:27 UTC, merged